[package]
name = "simple-math"
version = "0.1.0"
authors = ["jD91mZM2 <me@krake.one>"]
license = "MIT"

[dependencies]
bigdecimal = "0.0"
num = "0.1"
rustyline = "1.0"
simple_math_lib = { path = "simple-math-lib" }
