[package]
authors = ["jD91mZM2 <me@krake.one>"]
license = "MIT"
name = "simple-math"
version = "0.1.0"
[dependencies]
bigdecimal = "0.0.10"
num = "0.1.42"
rustyline = "1.0.0"

[dependencies.simple_math_lib]
path = "simple-math-lib"
